# Generated by Django 4.0.3 on 2022-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
